"""Add publication fields to news table

Revision ID: dc466934dea5
Revises: acb5cadb7875
Create Date: 2025-07-07 02:42:54.470160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc466934dea5'
down_revision = 'acb5cadb7875'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('is_published', sa.Boolean(), nullable=True))
    op.add_column('news', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'published_at')
    op.drop_column('news', 'is_published')
    # ### end Alembic commands ### 