"""
Модуль pipeline - организация цепочки обработки новостей.

Последовательность:
1. Scout - сбор новостей из различных источников
2. Filter - фильтрация релевантных новостей через Flowise
3. Copywriter - создание постов из отфильтрованных новостей

Обеспечивает логирование и отслеживание процесса на каждом этапе.
"""

from typing import List, Dict, Optional
from loguru import logger
from datetime import datetime
from pathlib import Path

from .scout import collect_insights
from .filter import filter_news_with_flowise
from .copywriter import call_flowise_copywriter
from .image_generator import generate_image_for_post


def save_news_to_markdown(articles: List[Dict[str, str]], markdown_file: str = "news_digest.md") -> None:
    """
    Сохраняет новости с изображениями в markdown файл.
    
    Args:
        articles: Список статей с постами и изображениями
        markdown_file: Путь к markdown файлу
    """
    markdown_path = Path(markdown_file)
    
    # Создаем заголовок если файл новый
    if not markdown_path.exists():
        with open(markdown_path, 'w', encoding='utf-8') as f:
            f.write("# News Digest\n\n")
            f.write("Generated by SMM Agents\n\n")
            f.write("---\n\n")
    
    # Добавляем новые статьи в конец файла
    with open(markdown_path, 'a', encoding='utf-8') as f:
        f.write(f"## Digest от {datetime.now().strftime('%Y-%m-%d %H:%M')}\n\n")
        
        for idx, article in enumerate(articles, 1):
            logger.debug(f"Сохраняем статью в markdown: {article.keys()}")
            logger.debug(f"post_content длина: {len(article.get('post_content', ''))}")
            
            f.write(f"### {idx}. {article['title']}\n\n")
            
            # Добавляем изображение если есть
            if article.get('image_path'):
                # Используем относительный путь для markdown
                image_path = Path(article['image_path']).name
                f.write(f"![Изображение](./{image_path})\n\n")
            
            f.write(f"**Источник:** [{article['url']}]({article['url']})\n\n")
            
            # Проверяем есть ли контент поста
            post_content = article.get('post_content', '')
            if post_content:
                f.write(f"{post_content}\n\n")
            else:
                # Если нет post_content, используем summary как fallback
                summary = article.get('summary', '')
                if summary:
                    f.write(f"**Краткое содержание:**\n{summary}\n\n")
                else:
                    f.write("Содержание недоступно.\n\n")
            
            f.write("---\n\n")
        
        f.write("\n")
    
    logger.info(f"✅ Сохранено {len(articles)} новостей в {markdown_path}")


class NewsPipeline:
    """
    Класс для управления цепочкой обработки новостей.
    
    Координирует работу всех агентов и обеспечивает передачу данных между ними.
    """
    
    def __init__(self, 
                 flowise_host: str, 
                 flowise_filter_id: str, 
                 flowise_copywriter_id: str,
                 image_config: Optional[Dict] = None):
        """
        Инициализация pipeline с настройками Flowise и генерации изображений.
        
        Args:
            flowise_host: Хост Flowise API
            flowise_filter_id: ID потока для фильтрации
            flowise_copywriter_id: ID потока для копирайтинга
            image_config: Конфигурация для генерации изображений
        """
        self.flowise_host = flowise_host
        self.flowise_filter_id = flowise_filter_id
        self.flowise_copywriter_id = flowise_copywriter_id
        self.image_config = image_config or {}
    
    def run_scout_stage(self, 
                       keywords: List[str],
                       google_api: Optional[str] = None,
                       google_cse: Optional[str] = None,
                       rss_feeds: Optional[List[str]] = None,
                       rss_hours: int = 72,
                       max_per_source: int = 5) -> List[Dict[str, str]]:
        """
        Этап 1: Сбор новостей через Scout агента.
        
        Args:
            keywords: Ключевые слова для поиска
            google_api: Google API ключ
            google_cse: Google Custom Search Engine ID
            rss_feeds: Список RSS лент
            rss_hours: Период в часах для RSS
            max_per_source: Максимум статей с источника
            
        Returns:
            List[Dict]: Собранные статьи
        """
        logger.info("🔍 Этап 1: Начинаем сбор новостей (Scout)")
        
        articles = collect_insights(
            keywords=keywords,
            google_api=google_api,
            google_cse=google_cse,
            rss_feeds=rss_feeds,
            rss_hours=rss_hours,
            max_per_source=max_per_source
        )
        
        logger.info(f"✅ Scout: собрано {len(articles)} статей")
        return articles
    
    def run_filter_stage(self, articles: List[Dict[str, str]]) -> List[Dict[str, str]]:
        """
        Этап 2: Фильтрация релевантных новостей через Filter агента.
        
        Args:
            articles: Статьи от Scout агента
            
        Returns:
            List[Dict]: Отфильтрованные статьи
        """
        logger.info("🔍 Этап 2: Начинаем фильтрацию новостей (Filter)")
        
        if not articles:
            logger.warning("⚠️ Нет статей для фильтрации")
            return []
        
        filtered_articles = filter_news_with_flowise(
            articles=articles,
            flow_id=self.flowise_filter_id,
            flowise_host=self.flowise_host
        )
        
        logger.info(f"✅ Filter: прошло фильтр {len(filtered_articles)} из {len(articles)} статей")
        return filtered_articles
    
    def run_copywriter_stage(self, articles: List[Dict[str, str]]) -> List[Dict[str, str]]:
        """
        Этап 3: Создание постов через Copywriter агента.
        
        Args:
            articles: Отфильтрованные статьи от Filter агента
            
        Returns:
            List[Dict]: Статьи с созданными постами
        """
        logger.info("✍️ Этап 3: Начинаем создание постов (Copywriter)")
        
        if not articles:
            logger.warning("⚠️ Нет статей для создания постов")
            return []
        
        articles_with_posts = []
        
        for idx, article in enumerate(articles, 1):
            logger.debug(f"Создаем пост для статьи {idx}/{len(articles)}: {article['title'][:50]}...")
            
            try:
                copywriter_result = call_flowise_copywriter(
                    flow_id=self.flowise_copywriter_id,
                    article=article,
                    flowise_host=self.flowise_host
                )
                
                # Добавляем созданный пост и идею изображения к статье
                article_with_post = article.copy()
                article_with_post['post_content'] = copywriter_result['post']
                article_with_post['image_idea'] = copywriter_result['image_idea']
                articles_with_posts.append(article_with_post)
                
                logger.debug(f"✅ Пост создан для: {article['title'][:50]}...")
                
            except Exception as e:
                logger.error(f"❌ Ошибка создания поста для {article['title'][:50]}...: {e}")
                continue
        
        logger.info(f"✅ Copywriter: создано {len(articles_with_posts)} постов из {len(articles)} статей")
        return articles_with_posts
    
    def run_image_generator_stage(self, articles: List[Dict[str, str]]) -> List[Dict[str, str]]:
        """
        Этап 4: Генерация изображений для постов через OpenAI DALL-E.
        
        Args:
            articles: Статьи с постами от Copywriter агента
            
        Returns:
            List[Dict]: Статьи с изображениями
        """
        logger.info("🎨 Этап 4: Начинаем генерацию изображений (OpenAI DALL-E)")
        
        if not articles:
            logger.warning("⚠️ Нет статей для генерации изображений")
            return []
        
        if not self.image_config.get("enabled", False):
            logger.info("ℹ️ Генерация изображений отключена")
            return articles
        
        # Получаем API key для OpenAI
        openai_api_key = self.image_config.get("openai_api_key")
        if not openai_api_key:
            logger.error("❌ Не указан OpenAI API key для генерации изображений")
            return articles
        
        articles_with_images = []
        
        for idx, article in enumerate(articles, 1):
            logger.debug(f"Генерируем изображение для статьи {idx}/{len(articles)}: {article['title'][:50]}...")
            
            try:
                # Генерируем изображение используя идею от копирайтера
                image_path = generate_image_for_post(
                    image_idea=article['image_idea'],
                    api_key=openai_api_key,
                    **self.image_config
                )
                
                # Добавляем путь к изображению
                article_with_image = article.copy()
                article_with_image['image_path'] = image_path
                articles_with_images.append(article_with_image)
                
                if image_path:
                    logger.debug(f"✅ Изображение создано: {image_path}")
                else:
                    logger.debug("❌ Не удалось создать изображение")
                
            except Exception as e:
                logger.error(f"❌ Ошибка генерации изображения для {article['title'][:50]}...: {e}")
                # Добавляем статью без изображения
                article_copy = article.copy()
                article_copy['image_path'] = None
                articles_with_images.append(article_copy)
        
        successful_images = len([a for a in articles_with_images if a.get('image_path')])
        logger.info(f"✅ Генерация изображений: создано {successful_images} из {len(articles)} изображений")
        
        return articles_with_images
    
    def run_full_pipeline(self,
                         keywords: List[str],
                         google_api: Optional[str] = None,
                         google_cse: Optional[str] = None,
                         rss_feeds: Optional[List[str]] = None,
                         rss_hours: int = 72,
                         max_per_source: int = 5) -> List[Dict[str, str]]:
        """
        Запускает полную цепочку обработки: Scout → Filter → Copywriter.
        
        Args:
            keywords: Ключевые слова для поиска
            google_api: Google API ключ  
            google_cse: Google Custom Search Engine ID
            rss_feeds: Список RSS лент
            rss_hours: Период в часах для RSS
            max_per_source: Максимум статей с источника
            
        Returns:
            List[Dict]: Финальные статьи с постами
        """
        logger.info("🚀 Запускаем полную цепочку обработки новостей")
        pipeline_start_time = logger.bind(stage="pipeline").info
        
        # Этап 1: Scout - сбор новостей
        articles = self.run_scout_stage(
            keywords=keywords,
            google_api=google_api,
            google_cse=google_cse,
            rss_feeds=rss_feeds,
            rss_hours=rss_hours,
            max_per_source=max_per_source
        )
        
        if not articles:
            logger.warning("⚠️ Pipeline остановлен: Scout не нашел статей")
            return []
        
        # Этап 2: Filter - фильтрация релевантных
        filtered_articles = self.run_filter_stage(articles)
        
        if not filtered_articles:
            logger.warning("⚠️ Pipeline остановлен: Filter не пропустил ни одной статьи")
            return []
        
        # Этап 3: Copywriter - создание постов
        articles_with_posts = self.run_copywriter_stage(filtered_articles)
        
        if not articles_with_posts:
            logger.warning("⚠️ Pipeline остановлен: Copywriter не создал ни одного поста")
            return []
        
        # Этап 4: Image Generator - создание изображений
        final_articles = self.run_image_generator_stage(articles_with_posts)
        
        # Итоговая статистика
        successful_images = len([a for a in final_articles if a.get('image_path')])
        logger.info(f"🎉 Pipeline завершен успешно!")
        logger.info(f"📊 Статистика: {len(articles)} собрано → {len(filtered_articles)} отфильтровано → {len(articles_with_posts)} постов → {successful_images} изображений")
        
        return final_articles


def run_news_pipeline(keywords: List[str],
                     flowise_host: str,
                     flowise_filter_id: str,
                     flowise_copywriter_id: str,
                     google_api: Optional[str] = None,
                     google_cse: Optional[str] = None,
                     rss_feeds: Optional[List[str]] = None,
                     rss_hours: int = 72,
                     max_per_source: int = 5,
                     image_config: Optional[Dict] = None,
                     save_to_markdown: bool = True,
                     markdown_file: str = "news_digest.md") -> List[Dict[str, str]]:
    """
    Упрощенная функция для запуска полной цепочки обработки новостей.
    
    Args:
        keywords: Ключевые слова для поиска
        flowise_host: Хост Flowise API
        flowise_filter_id: ID потока для фильтрации
        flowise_copywriter_id: ID потока для копирайтинга
        google_api: Google API ключ
        google_cse: Google Custom Search Engine ID  
        rss_feeds: Список RSS лент
        rss_hours: Период в часах для RSS фильтрации
        max_per_source: Максимум статей с источника
        image_config: Конфигурация для генерации изображений
        save_to_markdown: Сохранять ли результаты в markdown файл
        markdown_file: Путь к markdown файлу
        
    Returns:
        List[Dict]: Готовые посты с изображениями
    """
    pipeline = NewsPipeline(
        flowise_host=flowise_host,
        flowise_filter_id=flowise_filter_id,
        flowise_copywriter_id=flowise_copywriter_id,
        image_config=image_config
    )
    
    results = pipeline.run_full_pipeline(
        keywords=keywords,
        google_api=google_api,
        google_cse=google_cse,
        rss_feeds=rss_feeds,
        rss_hours=rss_hours,
        max_per_source=max_per_source
    )
    
    # Сохраняем результаты в markdown файл
    if save_to_markdown and results:
        save_news_to_markdown(results, markdown_file)
    
    return results